application: property-searchengine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /sitemap\.xml
  static_files: sitemap.xml
  upload: sitemap\.xml   

- url: /
  static_files: index.html
  upload: index.html

- url: /lang-CA.html
  static_files: lang-CA.html
  upload: lang-CA.html

- url: /index.html
  static_files: index.html
  upload: index.html  

- url: /stylesheet
  static_dir: stylesheet

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /BingSiteAuth.xml
  static_files: BingSiteAuth.xml
  upload: BingSiteAuth.xml

- url: /lang/ca.html
  static_files: ca.html
  upload: ca.html

- url: /mywot1d42add482d42c8349a9.html
  static_files: mywot1d42add482d42c8349a9.html
  upload: mywot1d42add482d42c8349a9.html   



